### ISSUE TITLE
Error on x64.asm

### ISSUE THREAD

**Issue by eix128** [Kelvinhack/DeviceMon#2]
Hi i got error on AsmInvept function and 
AsmInvvpid

  ; unsigned char __stdcall AsmInvept(
  ;     _In_ InvEptType invept_type,
  ;     _In_ const InvEptDescriptor *invept_descriptor);
  AsmInvept PROC
      invept ecx, oword ptr [rdx]
      jz errorWithCode        ; if (ZF) jmp
      jc errorWithoutCode     ; if (CF) jmp
      xor rax, rax            ; return VMX_OK
      ret
  
  errorWithoutCode:
      mov rax, VMX_ERROR_WITHOUT_STATUS
      ret
  
  errorWithCode:
      mov rax, VMX_ERROR_WITH_STATUS
      ret
  AsmInvept ENDP
  
  
  
  
  
  
  ; unsigned char __stdcall AsmInvvpid(
  ;     _In_ InvVpidType invvpid_type,
  ;     _In_ const InvVpidDescriptor *invvpid_descriptor);
  AsmInvvpid PROC
      invvpid ecx, oword ptr [rdx]
      jz errorWithCode        ; if (ZF) jmp
      jc errorWithoutCode     ; if (CF) jmp
      xor rax, rax            ; return VMX_OK
      ret
  
  errorWithoutCode:
      mov rax, VMX_ERROR_WITHOUT_STATUS
      ret
  
  errorWithCode:
      mov rax, VMX_ERROR_WITH_STATUS
      ret
  AsmInvvpid ENDP
  
  

Error on:
1-)
AsmInvept PROC
    invept ecx, oword ptr [rdx] <= Invalid operand size for instruction

2-)
AsmInvvpid PROC
    invvpid ecx, oword ptr [rdx] <=  Invalid operand size for instruction

**Comment by tandasat** [comment]
Try using `rcx` instead of `ecx`

**Comment by eix128** [comment]
I replaced:
AsmInvept:
    ; invept ecx, oword ptr [rdx]
    db  66h, 0fh, 38h, 80h, 0ah


AsmInvvpid
    ; invvpid rcx, oword ptr [rdx]
    db  66h, 0fh, 38h, 81h, 0ah
