### ISSUE TITLE
DeviceMon R9 295x2 GPU Sniffing and  manipulating for overclock

### ISSUE THREAD

**Issue by eix128** [Kelvinhack/DeviceMon#3]
Hi , i wanted to use DeviceMon for overclocking my own R9 GPUs.

I have found this datasheet
https://storage-asset.msi.com/datasheet/vga/global/R9-295X2-8GD5.pdf

But i dont get any information for
UINT8 BarOffset[MAX_BAR_INDEX]; // BAR offset in PCI Config , check your chipset datasheet
AND
UINT8 BarCount; // Number of BAR in PCI Config , check your chipset datasheet

where is this information on datasheet R9 295x2 ?

typedef struct _PCI_MONITOR_CFG
{
UINT8 BusNumber; // Device Bus
UINT8 DeviceNum; // Device Number
UINT8 FuncNum; // Device Function

UINT8 BarOffset[MAX_BAR_INDEX]; // BAR offset in PCI Config , check your chipset datasheet
// By default is 6 32bit BAR, if your device is 64bit BAR maxium is 3
// for 64bit, please adding BarAddressWidth
// LOWER and UPPER offset have to be in order as IntelMeDeviceInfo

UINT8 BarCount; // Number of BAR in PCI Config , check your chipset datasheet
ULONG64 BarAddress[MAX_BAR_INDEX]; // Obtained BAR address, it will be filled out runtime
ULONG64 BarLimit[MAX_BAR_INDEX]; // Obtained BAR size , it will be filled out runtime

MMIOCALLBACK Callback; // MMIO handler
ULONG BarAddressWidth[MAX_BAR_INDEX]; // 0 by default, PCI_64BIT_DEVICE affect BarOffset parsing n, n+1 => 64bit

OFFSETMAKECALLBACK Callback2; // callback that indicate offset is 64bit BAR
// offset combination is compatible for those 64bit combined BAR,
// and it should take device-dependent bitwise operation.
}PCIMONITORCFG, *PPCIMONITORCFG;

**Comment by KelvinMsft** [comment]
I think which is not the datasheet you need to read. Also, I wonder if AMD actually released the datasheet of their GPU.

**Comment by eix128** [comment]
Where is the datasheet location for r9 295x2 that i can get all information i need for devicemon ?

**Comment by KelvinMsft** [comment]
you might have to either find them on the AMD official website or non-disclosed by AMD.
